added files to practice_5
MariaPonomarenko38/Ponomarenko_pmi25 pull request #10
Opened 2020-10-17 08:30 UTC by MariaPonomarenko38

2020-10-24 20:04 UTC, tetianastoyko requested changes

2020-10-24 20:04 UTC, tetianastoyko commented on practice/practice_5/strategy_main.py
> +def strategy1(self):
Повинні існувати 3 класи: абстрактний клас - стратегія, 2 класи, які перевантажать метод абстрактного класу - власне 2 стратегії
1 клас - Context, Який буде зберігати вибрану стратегію

2020-10-24 20:04 UTC, tetianastoyko commented on practice/practice_5/strategy_main.py
> +def strategy1(self):
Ці всі класи по окремих файлах

2020-10-25 11:08 UTC, MariaPonomarenko38 commented on practice/practice_5/strategy_main.py
> +def strategy1(self):
Пофіксила

2020-11-23 11:21 UTC, merged