added files to programming_5
MariaPonomarenko38/Ponomarenko_pmi25 pull request #9
Opened 2020-10-14 14:46 UTC by MariaPonomarenko38

2020-10-24 20:09 UTC, tetianastoyko requested changes

2020-10-24 20:09 UTC, tetianastoyko commented on programming/programming_5/validation1.py
> +    @validate_id
декоратори маються бути використані в класах, а не тут

2020-10-25 11:09 UTC, MariaPonomarenko38 commented on programming/programming_5/validation1.py
> +    @validate_id
Пофіксила

2020-11-02 10:07 UTC, tetianastoyko requested changes

2020-11-02 10:07 UTC, tetianastoyko commented on programming/programming_5/online_meeting.py
> +    @validate_all
має бути на кожен setter повішаний декоратор, а не 1 загальний

2020-11-16 13:00 UTC, merged